"""
Django settings for aquavana project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import io
import os
import platform
import sys

import environ
import google.auth

from pathlib import Path
from google.cloud import secretmanager
from django.contrib.messages import constants as messages
from google.oauth2 import service_account
from django.contrib.messages import constants as messages
from django.utils.translation import ugettext_lazy as _

ALLOWED_HOSTS = ["*"]


def is_local_run():
    return (os.getenv('DJANGO_DEVELOPMENT', False) == 'true' or not os.getenv("USE_CLOUD_SQL_AUTH_PROXY", False)) \
        and platform.system().lower() == 'darwin'


if is_local_run():
    print('############################')
    print(' RUNNING ON DEV ENVIRONMENT')
    print('############################')
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = 'django-insecure-0x!lmi9jtqlqf3=t_mvay&*vow4*%t737nqryeaj^7_++2x!)l'
    DEBUG = True

    BASE_DIR = Path(__file__).resolve().parent.parent

    # Application definition
    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        'django.contrib.humanize',
        'django.contrib.sites',
        # 'crispy_forms',
        # 'rest_framework',
        # 'django_filters',
        # 'corsheaders',
        "storages",
        # 'widget_tweaks',
        "aquavana",
        # reversion -- https://django-reversion.readthedocs.io/en/stable/api.html
        # 'reversion',
        # templates
        # apps
        # 'authentication.apps.AuthenticationConfig',
        # 'layouts.apps.LayoutsConfig',
    ]
    CRISPY_TEMPLATE_PACK = 'bootstrap4'
    MIDDLEWARE = [
        # 'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',
        "django.middleware.security.SecurityMiddleware",
        'whitenoise.middleware.WhiteNoiseMiddleware',
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        # 'django.middleware.locale.LocaleMiddleware',
    ]
    ROOT_URLCONF = "aquavana.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": ['templates'],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    # 'mysite.context_processors.constant_values',
                ],
            },
        },
    ]
    WSGI_APPLICATION = "aquavana.wsgi.application"

    # Database
    # Use django-environ to parse the connection string
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'aquavana',
            'HOST': 'localhost',
            'POST': '5432',
        },
    }

    # Password validation
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    LANGUAGE_CODE = 'th-TH'
    TIME_ZONE = 'Asia/Bangkok'
    USE_I18N = True
    USE_TZ = True
    USE_L10N = False
    SITE_ID = 1
    DATE_INPUT_FORMATS = ['%d/%m/%Y']


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/4.0/howto/static-files/
    # STATIC_ROOT = os.path.join(BASE_DIR, "static")
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [
        BASE_DIR / 'static/',
    ]

    # Media settings
    # MEDIA_ROOT = BASE_DIR / 'media'
    MEDIA_URL = 'media/'

    # Messages
    MESSAGE_TAGS = {
        messages.DEBUG: 'alert-info',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
    }

    REST_FRAMEWORK = {
        # Use Django's standard `django.contrib.auth` permissions,
        # or allow read-only access for unauthenticated users.
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        ],
        'DEFAULT_FILTER_BACKENDS': (
            'django_filters.rest_framework.DjangoFilterBackend',
        ),
    }
else:
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # print('###########################')
    # print(BASE_DIR)
    # print('###########################')

    # [START cloudrun_django_secret_config]
    # SECURITY WARNING: don't run with debug turned on in production!
    # Change this to "False" when you are ready for production
    env = environ.Env(DEBUG=(bool, True))
    env_file = os.path.join(BASE_DIR, ".env")

    # Attempt to load the Project ID into the environment, safely failing on error.
    try:
        _, os.environ["GOOGLE_CLOUD_PROJECT"] = google.auth.default()
    except google.auth.exceptions.DefaultCredentialsError:
        pass

    if os.path.isfile(env_file):
        # Use a local secret file, if provided
        env.read_env(env_file)
    # [START_EXCLUDE]
    elif os.getenv("TRAMPOLINE_CI", None):
        # Create local settings if running with CI, for unit testing
        placeholder = (
            f"SECRET_KEY=a\n"
            "GS_BUCKET_NAME=None\n"
            f"DATABASE_URL=sqlite://{os.path.join(BASE_DIR, 'db.sqlite3')}"
        )
        env.read_env(io.StringIO(placeholder))
    # [END_EXCLUDE]
    elif os.environ.get("GOOGLE_CLOUD_PROJECT", None):
        # Pull secrets from Secret Manager
        project_id = os.environ.get("GOOGLE_CLOUD_PROJECT")
        client = secretmanager.SecretManagerServiceClient()
        settings_name = os.environ.get("SETTINGS_NAME", "aquavana_settings")
        name = f"projects/{project_id}/secrets/{settings_name}/versions/latest"
        payload = client.access_secret_version(name=name).payload.data.decode("UTF-8")
        env.read_env(io.StringIO(payload))
    else:
        raise Exception("No local .env or GOOGLE_CLOUD_PROJECT detected. No secrets found.")
    # [END cloudrun_django_secret_config]

    SECRET_KEY = env("SECRET_KEY")
    DEBUG = env("DEBUG")

    # Application definition
    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        'django.contrib.humanize',
        'django.contrib.sites',
        # 'crispy_forms',
        # 'rest_framework',
        # 'django_filters',
        # 'corsheaders',
        "storages",
        # 'widget_tweaks',
        "aquavana",
        # reversion -- https://django-reversion.readthedocs.io/en/stable/api.html
        # 'reversion',
        # templates
        # apps
        # 'authentication.apps.AuthenticationConfig',
        # 'layouts.apps.LayoutsConfig',
    ]
    CRISPY_TEMPLATE_PACK = 'bootstrap4'
    MIDDLEWARE = [
        # 'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',
        "django.middleware.security.SecurityMiddleware",
        'whitenoise.middleware.WhiteNoiseMiddleware',
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        # 'django.middleware.locale.LocaleMiddleware',
    ]
    ROOT_URLCONF = "aquavana.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": ['templates'],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    # 'mysite.context_processors.constant_values',
                ],
            },
        },
    ]
    WSGI_APPLICATION = "aquavana.wsgi.application"

    # Database
    # [START cloudrun_django_database_config]
    # Use django-environ to parse the connection string
    DATABASES = {"default": env.db()}

    # If the flag as been set, configure to use proxy
    if os.getenv("USE_CLOUD_SQL_AUTH_PROXY", None):
        DATABASES["default"]["HOST"] = "127.0.0.1"
        DATABASES["default"]["PORT"] = 5432
    # [END cloudrun_django_database_config]

    # Password validation
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    LANGUAGE_CODE = 'th-TH'
    TIME_ZONE = 'Asia/Bangkok'
    USE_I18N = True
    USE_TZ = True
    USE_L10N = False
    SITE_ID = 1
    DATE_INPUT_FORMATS = ['%d/%m/%Y']

    # Static files (CSS, JavaScript, Images)
    # [START cloudrun_django_static_config]
    # Define static storage via django-storages[google]
    GS_BUCKET_NAME = env("GS_BUCKET_NAME")
    # GS_BUCKET_NAME = 'accounting-bucket'
    GS_PROJECT_ID = 'dev-server-330909'
    # STATIC_ROOT = 'static/'
    STATIC_URL = "/static/"
    STATICFILES_DIRS = [
        # add other static folders
        # BASE_DIR / 'carzone/static',
    ]
    DEFAULT_FILE_STORAGE = "aquavana.gcloud_storages.GoogleCloudMediaStorage"
    STATICFILES_STORAGE = "aquavana.gcloud_storages.GoogleCloudStaticStorage"
    GS_DEFAULT_ACL = "publicRead"
    # [END cloudrun_django_static_config]

    # Media settings
    # MEDIA_ROOT = 'media/'
    MEDIA_URL = "/media/"
    # Add an unique ID to a file name if same file name exists
    GS_FILE_OVERWRITE = False
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
        os.path.join(BASE_DIR, 'gcs_credentials.json'),
    )

    # Collect static files on local storages
    if BASE_DIR.find('atthachet') > -1 or BASE_DIR.find('Developer') > -1:
        STATIC_ROOT = os.path.join(BASE_DIR, "static")
        STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    #     DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

    # Messages
    MESSAGE_TAGS = {
        messages.DEBUG: 'alert-info',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
    }

    REST_FRAMEWORK = {
        # Use Django's standard `django.contrib.auth` permissions,
        # or allow read-only access for unauthenticated users.
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        ],
        'DEFAULT_FILTER_BACKENDS': (
            'django_filters.rest_framework.DjangoFilterBackend',
        ),
    }

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'atthachet@mbc.co.th'
EMAIL_HOST_PASSWORD = 'AddictO5'
DEFAULT_FROM_EMAIL = 'atthachet@mbc.co.th'
SERVER_EMAIL = 'atthachet@mbc.co.th'

LOGIN_URL = 'auth-login'
LOGIN_REDIRECT_URL = 'auth-login'
LOGOUT_REDIRECT_URL = '/'

SESSION_IDLE_TIMEOUT = 10 * 60
